version: "3"
services:
    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        ports:
          - 3000:3000
        networks:
          - example



    nginx:
        container_name: my_nginx
        image: getting-started
        ports:
          - 80:80
        networks:
          - example

networks:
  example:
    driver: bridge

